// <auto-generated />
namespace Appli.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isAnnonceur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isAnnonceur));
        
        string IMigrationMetadata.Id
        {
            get { return "202001111559482_isAnnonceur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
