/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
--use [TnTMarketDB]
--use Shak29_tntmarket_testdb

SELECT *  FROM [dbo].[LocationRef]
SELECT distinct ZoneName  FROM [dbo].[LocationRef]

----------   RESET TOUT

--
delete [dbo].[LocationRef]
DBCC CHECKIDENT ('[dbo].[LocationRef]', RESEED, 0)
GO

--------------------------------------  INIT DES TYPES D ANNONCES
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Abercombie', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Baie Grande Rivière Nord Ouest', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Bell Village', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Cantin''s Peak', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Cassis', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Champ de Mars', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Colline Monneron', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Fort Adélaïde', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Fort George', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Fort Victoria', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Fort Williams', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Grand Glacis', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Ile aux Tonneliers', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Ile Bakly', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'La Fenêtre ', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Montagne du Pouce', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Pieter Both', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Plaine Lauzun', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Plaine Verte', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Port Louis', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Priest Peak', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Roche Bois', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Ste Croix', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Tranquebar', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Trou Fanfaron', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Valée des Prêtres', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Valée du Pouce', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Valée Pitot', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Port-Louis', 'Virgin''s Peak', 'Zone de Port-Louis' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Arsenal', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Baie aux Tortues', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Baie du Tombeau', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Balaclava', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bassin Loulou', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bellevue Harel', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bellevue Pitot', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bois Mangues', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bois Marchand', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bois Pignolet', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bois Rouge', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Bon Air', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Butte aux Papayes', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Calebasses', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Camp Scipion', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Canton Nancy', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Chateau de Villebague', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Congomah', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Crève Coeur', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'd''Epinay', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Eaux Bouillies', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Fond du Sac', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Fort Albert', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Ganachaud', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Gowsal', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Grande Rosalie', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'La Louisa', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'La Nicolière', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'La Paix', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Le Goulet', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Le Plessis', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Les Mariannes', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Mon Gout', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Mon Rocher', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Mont Choisy', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Mont Piton', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Montagne Callebasses', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Montagne Longue', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Morcellement St André', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Moulin à Poudre', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Notre Dame', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Pamplemousses', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Petit Galopin', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Petite Julie', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Plaine des Calebasses', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Plaine des Papayes', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Pointe aux Canonniers', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Pointe aux Piments', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Pointe Roches Noires', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Riche Terre', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Roche Bois', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Rouge Terre', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Ruisseau Rose', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Solitude', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Terre Rouge', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'The Mount', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Triolet', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Trou aux Biches', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Valton', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Ville Valio', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Pamplemousse', 'Villebague', 'Zone de Pamplemousse' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Amaury', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Amitié', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Anse Bonsergent', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Anse la raie', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Antoinette', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Barlow', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bassin Bernard', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bassin Goëmons', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bassin Humbert', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Beau Manguier', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Beau Séjour', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bellevue Maurel', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Belmont', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bon Espoir', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Bras de mer des Frégates', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Butte à Herbe', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Calodyne', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Camp Pavé', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Cap Malheureux', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Coin de Mire', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Cottage', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Espérance Trébuchet', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Forbach', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Forbach Hill', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Gokoola', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Goodlands', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Grand Baie', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Grand Gaube', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Haute Rive', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Hermitage', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Ile d''Ambre', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Ile Plate', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Ilot du Mort', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Ilot Gabriel', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Labourdonnais', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mapou', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Melville', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mlle Jeanne', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mon Loisir', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mon Songe', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mont Oreb', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Mont Piton', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Moulin à Vent', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pavillon', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Perebeyre', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Petit Paquet', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Petit Raffray', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Piton', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Plaine des Roches', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe aux Roches', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Bernard', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Bonhomme', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Butte aux Sable', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe d''Azur', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe de l''Embarcadère', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Eglise', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Lascar', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe l''Hortal', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Madras', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Pointe Oscorne', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Poudre d''Or', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Poudre d''or Hamlet', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Réunion Maurel', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Rivière du Rempart', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Roche Terre', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Roches Noires', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Schoenfeld', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Sottise', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'St François', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'The Vale', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rivière du Rempart', 'Union Maurel', 'Zone de Rivière du Rempart' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Albion', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Anna', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Baie de la Grande Rivière Noire', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Baie de la Petite Rivière', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Baie de la Petite Rivière Noire', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Baie du Tamarin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Bambous', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Beaux Songes', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Bel Air', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Belle Eau', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Belle Isle', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Belle Vue', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Cachette', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Camp Benoît', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Canot', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Castavelle', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Chamarel', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Chebel', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Clarence', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Coteau Raffin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Eau Bonne', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Eau Bouillie', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Flic en Flac', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Gorges de la Rivière Noire', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Grande Case Noyale', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Grande Rivière Noire', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Grandes Gorges', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Gros Cailloux', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Ile aux Bénitiers', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Ilot Fortier', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Ilot Fourneau', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Ilot Malais', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Chaumière', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Coupée St Martin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Crète', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Ferme', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Gaulette', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Mecque', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Mivoie', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'La Preneuse', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Laviléon', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Le Bosquet', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Le Morne Brabant', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'L''embrasure', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Les Salines', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Magenta', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Médine', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Mon Désir', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Mon Vallon', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Mont St Pierre', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Brise Fer', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Corps de Garde', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne du Rempart', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Jacquot', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Laporte', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Simonet', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagne Trois Mamelles', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montagnes Vacoas', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Montée Bois Puant', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Palma', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Palmyre', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Petit Moka', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Petit Verger', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Petite Case Noyale', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Petite Rivière', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Petite Rivière Noire', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Piton Canot', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Piton du Fouge', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Piton St Denis', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe aux Caves', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe aux Sables', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe Corail de la Prairie', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe de la Petite Rivière', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe des Pêcheurs', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe du Tamarin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe Marron', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe Moyenne', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Pointe Sud Ouest', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Richelieu', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Tamarin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Tamarin Estate', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Tamarin Falls', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Tour Martello de l''Harmonie', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Tourelle du Tamarin', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Trois Cavernes', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Wolmar', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Riviere noir', 'Yemen', 'Zone de Riviere noir' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Atelier', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Bagatelle', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Bananes', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Bassin', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Beard', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Beau Bassin', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Belle Terre', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Bigara', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Camp Fouquereau', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Camp Roche', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Candos', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Château Trianon', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Coriolis', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Coromandel', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Curepipe', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Eau Coulée', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Ebène', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Floréal', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Forest Side', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Galléa', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Glen Park', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Grand Bassin', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Henrietta', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Highlands', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'La Brasserie', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'La Caverne', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'La Croisée', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'La Louise', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'La Marie', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Ligne Barrique', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Mare aux Vacoas', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Mare Longue', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Mare Ory', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Mont Petit Malabar', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Mont Roches', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Montagne Lagrave', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Montagne Perruche', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Petit Camp', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Phoenix', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Plaine Raoul', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Plaine Sophie', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Plaisance', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Quatre Bornes', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Quinze Cantons', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Réservoir de Tamarin Falls', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Réunion', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'River Side', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Rose Hill', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Solférino', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'St Jean', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Stanley', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Trou aux Cerfs', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Trou de Madame Bouchet', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Vacoas', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Ville d''Avray', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Plaines Wilhems', 'Wooton', 'Zone de Plaines Wilhems' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Alma', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Anse Courtois', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Bar le Duc', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Beau Bois', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Belle Rive', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Bois Clair', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Bonne Veine', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Butte Chaumont', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Camp Thorel', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Cilline Alma', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Circonstance', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Côte d''Or', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Dubreuil', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Espérance', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Gingenbre', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Helvetia', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Hermitage', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Junction Peak', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'La Chartreuse', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'La Dagotière', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'La Laura', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'La Pipe', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'La Russie', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'l''Agrément', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'l''Avenir', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Le Bocage', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Le Réduit', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Magenta', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Malenga', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Martindale', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Melrose', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Midlands', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Minissy', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Moka', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Mon Désert Alma', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Mont Ida', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Montagne Blanche', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Montagne du Pouce', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Montagne la Terre', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Montagne les Deux Mamelles', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Montagne Ory', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Nouvelle Découverte', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pailles', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pépinière', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pépinière', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Petit paquet', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pic des Guibies', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pic Grand Fond', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Pic Seneque', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Piton du Milieu', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Providence', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Quartier Militaire', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Réservoir Piton Milieu', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Ripailles', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Rivière Baptiste', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Roselyn Cottage', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Salazie', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Sans Soucis', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'St Julien Hillock', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'St Pierre', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Valetta', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Verdun', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Verdun Hill', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Moka', 'Vuilemin', 'Zone de Moka' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Anse Cunat', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Argy', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Beau Champ', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Beau Rivage', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bel Air', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bel Etang', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Belle Mare', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Belle Rive', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Belle Rose', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Belvédère', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bois d''Oiseaux', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bois Jacot', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bon Accueil', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bonne Mère', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bramsthan', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bras de Mer Delcourt', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Bras d''Eau', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Brisée Verdière', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Camp de Masque', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Camp de Masque Pavé', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Camp Ithier', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Camp Marcelin', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Camp Marcellin', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Centre de Flacq', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Choisy', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Clemencia', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Constance', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Deep River', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ecroignard', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ernest Florent', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'F.U.E.L.', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Grande Retraite', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Grande Rivière Sud Est', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile aux Cerfs', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile aux Chats', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile aux Lubines', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile Camisard', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile de l''Est', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile Forancis', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ile Malino', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ilot des Roches', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Caroline', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Commune', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Gaité', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Laura', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Lucie Roy', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'La Nourrice', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Lalmatie', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'L''Aventure', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Lenferna', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Les Sept Chemins', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Lesur', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'l''Etoile', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'l''Unité', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mare aux Fougères', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mare aux Lubines', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mare d''Australia', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mare la Chaux', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mare Sarcelles', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Médine', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mont Barbe', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mont Couve', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mont Ravat', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Mont Villars', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Montagne Chat', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Montagne de la Nicolière', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Montagne Fayence', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Montagne Maurice', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Montagne Nouvelle Découverte', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Olivia', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Palmar', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pellegrin', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Petit Bois', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Petite Cabane', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Petite Retraite', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe aux Boeufs', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe de Flacq', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe de la Baterie', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe de Roches Noires', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe d''Esny', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe du Puit des Hollandais', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe Lafayette', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe Quatre Cocos', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe Radeau', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pointe Radeau', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pont Blanc', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pont Bon Dieu', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pont Lardier', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Pont Praslin', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Poste de Flacq', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Poste Lafayette', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Quatre Cocos', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Quatre Soeurs', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Queen Victoria', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Rich Fund', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Riche Mare', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Rivière Profonde', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Rivière Sèche', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Sébastopol', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'St Julien', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'St Julien d''Hotman', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Ste Ursule', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Flacq', 'Trou d''Eau Douce', 'Zone de Flacq' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Anse St Martin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Baie du Cap', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Baie du Jacotet', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bassin Blanc', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Baty Mare', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Beau Bois', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Beau Champ', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bel Air', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bel Ombre', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bénarès', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bois Chéri', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bois Sec', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Bon Courage', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Britannia', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Camp Diable', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Chamouny', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Château', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Chemin Grenier', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Choisy', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Colmar', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Cratère Kanaka', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Fantaisie', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Fontenelle', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Frederica', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Grand Bois', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Gris Gris', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Ilot Sanche', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Jurançon', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'La Flora', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'La Roche qui Pleure', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Le Petit Cap', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Les Mares', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Luchon', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Macondé', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Mare Anguilles', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Mont Blanc', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Mont Surinam', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Montagne Cocotte', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Montagne Savanne', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Piton Capote', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Piton Grand Bassin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Piton Poule', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Piton Savanne', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Plaine Champagne', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Pointe aux Roches', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Pointe Citronniers', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Pomponnette', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Riambel', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Riche Bois', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Rivière des Anguilles', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Rivière Dragon', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Rochester Falls', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Ruisseau des Créoles', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Savannah', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Souillac', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'St Aubin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'St Félix', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'St Félix', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'St Martin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'St Martin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Surinam', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Terracne', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Trou Desny', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Savanne', 'Union St Aubin', 'Zone de Savanne' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Anse Colas', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Anse du Grand Sable', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Anse Fauverelle', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Anse Hercule', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Anse Jonchée', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Astroea', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Bambous Virieux', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Barachois Rochecouste', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Beau Climat', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Beau Fond', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Beau Site', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Beau Vallon', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Bel Air', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Belle Vue', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Blue Bay', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Bois des Amourettes', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Bois d''Oiseaux', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Camp Carol', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Camp Poule', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Carreau Acacia', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Cent Gaulette', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Cluny', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Dalais', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Deux Bras', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Eau Bleue', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ferney', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Fressange', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Grand Sable', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Gros Billot', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Gros Bois', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile aux Aigrettes', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile aux Fous', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile aux Oiseaux', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile de la Passe', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile des deux Cocos', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile Marianne', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ile Vacoas', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ilot Chat', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ilot Flamants', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ilot Singe', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Joli Bois', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Barraque', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Cambuse', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Chaux', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Rampe', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Rosa', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'La Terre Rouge', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Le Bouchon', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Le Chaland', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Le Souffleur', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Le Val', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Le Vallon', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Leboeuf', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Les Mares', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'L''Escalier', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ligne Barin', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Madame Lolo', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mahébourg', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Malakoff', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mare Chicose', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mare d''Albert', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mare Tabac', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mon Désert', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mon Trésor', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mont des Hollandais', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mont Fertile', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne Bambou', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne Camisard', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne des Créoles', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne du Lion', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne Table à Perrot', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Montagne Vernon', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Mouchoir Rouge', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'New Grove', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Nouvelle France', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pavillon du Grand Port', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Petit Sable', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Piton Rouge', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Plaine Magnien', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Plaisance', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe aux Feuilles', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe aux Roches', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Bambou', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Brocus', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Chaour', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Corps de Garde', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe de la Colonie', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe des Deux Cocos', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe des Régates', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Desny', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe du Diable', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe du Hangard', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Jérôme', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pointe Vacoas', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pont Colville', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pont Molino', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Pont Naturel', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Riche en Eau', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Rivière des Créoles', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Rivière du Poste', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Rocher des Oiseaux', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Rose Belle', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ruisseau Copeau', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Savinia', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'St Hubert', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ste Hilaire', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ste Philomène', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Trois Boutiques', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Trou Beloute', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Trou Thomy', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Union Park', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Union Vale', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Vieux Grand Port', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Ville Noire', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Grand Port', 'Virginia', 'Zone de Grand Port' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Anse Ally ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Anse Quitor ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Anse-aux-Anglais ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Caverne Provert ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Citronnelle ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Grand Baie ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Grande Montagne ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Graviers ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'île aux Cocos ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Jeantac ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'La Ferme ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Mangues ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Maréchal ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Mont Lubin ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Palissade ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Petit Gabriel ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Plaine Caverne ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Pointe Coton ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Port Mathurin', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Port Sud-Est ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Saint-François ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Saint-Gabriel ', 'Zone de Rodrigues' )
INSERT INTO [dbo].[LocationRef] ( [ZoneName], [LocationName], [LocationDetails]) VALUES ('Rodrigues', 'Terre Rouge', 'Zone de Rodrigues' )

-------------  UPDATE ZoneRef

UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone1'  WHERE [ZoneName] = 'Port-Louis'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone2'  WHERE [ZoneName] = 'Pamplemousse'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone3'  WHERE [ZoneName] = 'Rivière du Rempart'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone4', [ZoneName]= 'Rivière noir'  WHERE [ZoneName] = 'Riviere noir'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone5'  WHERE [ZoneName] = 'Plaines Wilhems'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone6'  WHERE [ZoneName] = 'Moka'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone7'  WHERE [ZoneName] = 'Flacq'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone8'  WHERE [ZoneName] = 'Savanne'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone9' , [ZoneName] = 'Grand-Port'  WHERE [ZoneName] = 'Grand Port'
UPDATE [dbo].[LocationRef] SET [ZoneRef] = 'Zone10'  WHERE [ZoneName] = 'Rodrigues'

GO



